In [10]:
import numpy as np
a =[2,-1,5,4]
b= np.array(a)
print (b.reshape(4,1))

[[ 2]
 [-1]
 [ 5]
 [ 4]]


In [14]:
import numpy as np
a =[2,-1,5,4]
b= np.array(a)
print (b.reshape(-2,1))

[[ 2]
 [-1]
 [ 5]
 [ 4]]


In [29]:
import numpy
a = numpy.array([5,2,4,9])
b = numpy.array([19,29,100,7])
c = numpy.concatenate((a,b))
print (c)

[  5   2   4   9  19  29 100   7]


In [31]:
import numpy
a1 = numpy.array([[1,2],[3,4]])
b1 = numpy.array([[5,6],[7,8]])
c1 = numpy.concatenate((a1,b1))
print(c1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [32]:
import numpy
a = numpy.array([5,2,4,9])
b = numpy.array([19,29,100,7])
c = numpy.concatenate((a,b), axis =0)
print (c)

[  5   2   4   9  19  29 100   7]


In [34]:
import numpy
a1 = numpy.array([[1,2],[3,4]])
b1 = numpy.array([[5,6],[7,8]])
c1 = numpy.concatenate((a1,b1), axis =1)
print(c1)

[[1 2 5 6]
 [3 4 7 8]]


In [38]:
import numpy
a1 = ([[1,2],[3,4],[5,6]])
b1 = ([[7,8],[9,10],[11,12]])
c1 = numpy.concatenate((a1,b1),axis =1)
print  (c1)

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [41]:
import numpy
a1 = ([[1,2],[3,4],[5,6]])
b1 = ([[7,8],[9,10],[11,12]])
a = ([[13,14],[15,16],[17,18]])
c1 = numpy.concatenate((a1,b1,a),axis =1)
print  (c1)

[[ 1  2  7  8 13 14]
 [ 3  4  9 10 15 16]
 [ 5  6 11 12 17 18]]


In [44]:
aa = numpy .array([5,2,4,9])
bb = numpy .array ([19,29,100,7])
cc= numpy .stack((aa,bb),axis =1)
print(cc)

[[  5  19]
 [  2  29]
 [  4 100]
 [  9   7]]


In [49]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,3)
print (b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [50]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,5)
print (b)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [51]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,4)
print (b)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [52]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,6)
print (b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [53]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,7)
print (b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [54]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,20)
print (b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]


In [ ]:
import numpy as np
a= np.array([1,2,3,4,5,6])
b= np.array_split(a,3)
print (b)